name: MotiMusic
version: ${project.version}
main: fi.johvu.motimusic.MotiMusic
api-version: 1.15
authors: [Johvu, Kaap0]
commands:
  music:
permissions:
    music.start:
        description: Enables instruments
        default: op
    music.stop:
        description: Gives access to stop music sel
        default: op
